const crypto = require("crypto");
const express = require("express");
const dotenv = require("dotenv");
const path = require("path");
const business = require("./business");
const { buildPeachTemplatePayload, normalizePeachWebhook, publicWebhookAudit } = require("./peach");

dotenv.config();
const app = express();
const PORT = process.env.PORT || 3000;
const ZOZ_NAME = process.env.ZOZ_NAME || "ZOZ AI";
const WHATSAPP_API_VERSION = process.env.WHATSAPP_API_VERSION || "v23.0";
const PEACH_API_URL = "https://app.trypeach.io/api/v1/events";
const PEACH_TEMPLATE_ID = process.env.PEACH_TEMPLATE_ID || "";
const WHATSAPP_SEND_SECRET = process.env.WHATSAPP_SEND_SECRET || "";
app.use(express.json({ verify: (req, res, buffer) => { req.rawBody = Buffer.from(buffer); } }));
app.use(express.static(path.join(__dirname, "public")));

const KV_REST_API_URL = process.env.KV_REST_API_URL || process.env.ZOZ_KV_REST_API_URL;
const KV_REST_API_TOKEN = process.env.KV_REST_API_TOKEN || process.env.ZOZ_KV_REST_API_TOKEN;
const DATABASE_URL = process.env.DATABASE_URL || process.env.ZOZ_DATABASE_URL;
const persistence = { enabled: Boolean((KV_REST_API_URL && KV_REST_API_TOKEN) || DATABASE_URL), provider: DATABASE_URL ? "postgresql" : ((KV_REST_API_URL && KV_REST_API_TOKEN) ? "KV-compatible REST" : "memory"), key: process.env.ZOZ_STATE_KEY || "zoz-ai:state" };
const state = { name: ZOZ_NAME, status: "running", autonomy: true, financialApprovalRequired: true, jobs: [], approvals: [], audit: [], business: business.createBusinessState(), connectors: {
  github: { status: "connected", label: "GitHub", automation: "ready" }, vercel: { status: "deployed", label: "Vercel", automation: "deployment_verified" },
  database: { status: persistence.enabled ? "configured_unverified" : "needs_setup", label: "Database", automation: "verification_required" },
  whatsapp: { status: (process.env.PEACH_API_KEY && PEACH_TEMPLATE_ID) || (process.env.WHATSAPP_ACCESS_TOKEN && process.env.WHATSAPP_PHONE_NUMBER_ID) ? "configured_unverified" : "needs_setup", label: "WhatsApp", automation: "verification_required" },
  youtube: { status: process.env.YOUTUBE_ACCESS_TOKEN ? "configured_unverified" : "needs_setup", label: "YouTube", automation: "verification_required" },
  tiktok: { status: process.env.TIKTOK_ACCESS_TOKEN ? "configured_unverified" : "needs_setup", label: "TikTok", automation: "verification_required" },
  linkedin: { status: process.env.LINKEDIN_ACCESS_TOKEN ? "configured_unverified" : "needs_setup", label: "LinkedIn", automation: "verification_required" },
  shopify: { status: process.env.SHOPIFY_ACCESS_TOKEN ? "configured_unverified" : "needs_setup", label: "Shopify", automation: "verification_required" }
} };

function audit(event, details = {}) { const safe = { ...details }; for (const key of Object.keys(safe)) if (/key|token|secret|password|authorization|access/i.test(key)) delete safe[key]; state.audit.push({ id: `${Date.now()}-${state.audit.length}`, event, details: safe, at: new Date().toISOString() }); if (state.audit.length > 500) state.audit.splice(0, state.audit.length - 500); }
async function fetchJson(url, options = {}) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 8000); try { const response = await fetch(url, { ...options, signal: controller.signal }); const text = await response.text(); let body = null; try { body = text ? JSON.parse(text) : null; } catch { body = { text: text.slice(0, 300) }; } return { ok: response.ok, status: response.status, body }; } finally { clearTimeout(timer); } }
async function kvGet(key) { if (!KV_REST_API_URL || !KV_REST_API_TOKEN) return null; const base = KV_REST_API_URL.replace(/\/$/, ""); const response = await fetchJson(`${base}/get/${encodeURIComponent(key)}`, { headers: { Authorization: `Bearer ${KV_REST_API_TOKEN}` } }); if (!response.ok) throw new Error(`Persistence GET failed: ${response.status}`); return response.body; }
async function kvSet(key, value) { if (!KV_REST_API_URL || !KV_REST_API_TOKEN) return null; const base = KV_REST_API_URL.replace(/\/$/, ""); const response = await fetchJson(`${base}/set/${encodeURIComponent(key)}`, { method: "POST", headers: { Authorization: `Bearer ${KV_REST_API_TOKEN}`, "Content-Type": "application/json" }, body: JSON.stringify(value) }); if (!response.ok) throw new Error(`Persistence SET failed: ${response.status}`); return response.body; }
async function loadState() { if (!KV_REST_API_URL || !KV_REST_API_TOKEN) return; try { const result = await kvGet(persistence.key); if (result?.result) { const saved = typeof result.result === "string" ? JSON.parse(result.result) : result.result; if (saved && typeof saved === "object") { state.jobs = Array.isArray(saved.jobs) ? saved.jobs : []; state.approvals = Array.isArray(saved.approvals) ? saved.approvals : []; state.audit = Array.isArray(saved.audit) ? saved.audit.slice(-500) : []; if (saved.business && typeof saved.business === "object") state.business = { ...business.createBusinessState(), ...saved.business }; } } } catch (error) { audit("persistence_load_failed", { message: error.message }); } }
async function saveState() { if (!KV_REST_API_URL || !KV_REST_API_TOKEN) return; try { await kvSet(persistence.key, { ...state, savedAt: new Date().toISOString() }); } catch (error) { audit("persistence_save_failed", { message: error.message }); } }
function isFinanciallySensitive(text = "") { return /دفع|شراء|تحويل|سحب|استلام\s*أموال|استلام\s*اموال|بنك|بطاقة|bank|card|payment|purchase|transfer|withdraw/i.test(String(text)); }
function isValidWhatsAppSignature(req) { const secret = process.env.WHATSAPP_APP_SECRET; if (!secret) return true; const signature = String(req.get("x-hub-signature-256") || ""); if (!signature.startsWith("sha256=") || !req.rawBody) return false; const expected = `sha256=${crypto.createHmac("sha256", secret).update(req.rawBody).digest("hex")}`; const actualBuffer = Buffer.from(signature), expectedBuffer = Buffer.from(expected); return actualBuffer.length === expectedBuffer.length && crypto.timingSafeEqual(actualBuffer, expectedBuffer); }
function authorizeSecret(req, res, secret, errorCode = "unauthorized") { if (!secret) return res.status(503).json({ ok: false, error: "endpoint_secret_not_configured" }); const expected = `Bearer ${secret}`; const actual = String(req.get("authorization") || ""); const a = Buffer.from(actual), b = Buffer.from(expected); if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) return res.status(401).json({ ok: false, error: errorCode }); return null; }
function authorizeCron(req, res) { return authorizeSecret(req, res, process.env.CRON_SECRET, "unauthorized"); }
function peachConfigured() { return Boolean(process.env.PEACH_API_KEY && PEACH_TEMPLATE_ID); }

async function sendPeachTemplateMessage(to, options = {}) { if (!process.env.PEACH_API_KEY || !PEACH_TEMPLATE_ID) return { ok: false, status: 503, provider: "peach", error: "peach_credentials_or_template_missing" }; let payload; try { payload = buildPeachTemplatePayload({ to, templateId: PEACH_TEMPLATE_ID, liquidValues: options.liquidValues, name: options.name, email: options.email, metadata: options.metadata, businessPhoneNumber: process.env.PEACH_BUSINESS_PHONE_NUMBER, replyAutomationAppId: options.replyAutomationAppId }); } catch (error) { return { ok: false, status: 400, provider: "peach", error: error.message }; } const response = await fetchJson(PEACH_API_URL, { method: "POST", headers: { Authorization: process.env.PEACH_API_KEY, "Content-Type": "application/json" }, body: JSON.stringify(payload) }); audit("whatsapp_peach_outbound_attempt", { provider: "peach", ok: response.ok, httpStatus: response.status, hasLiquidValues: Object.keys(payload.template_message.liquid_values).length > 0 }); return { ok: response.ok, status: response.status, provider: "peach", messageId: response.body?.id || response.body?.message_id || response.body?.event_id || null, error: response.ok ? null : "peach_api_rejected_request" }; }
async function sendWhatsAppTextMeta(to, text) { if (!process.env.WHATSAPP_ACCESS_TOKEN || !process.env.WHATSAPP_PHONE_NUMBER_ID) return { ok: false, status: 503, provider: "meta", error: "whatsapp_credentials_missing" }; const url = `https://graph.facebook.com/${WHATSAPP_API_VERSION}/${encodeURIComponent(process.env.WHATSAPP_PHONE_NUMBER_ID)}/messages`; const response = await fetchJson(url, { method: "POST", headers: { Authorization: `Bearer ${process.env.WHATSAPP_ACCESS_TOKEN}`, "Content-Type": "application/json" }, body: JSON.stringify({ messaging_product: "whatsapp", recipient_type: "individual", to: String(to), type: "text", text: { preview_url: false, body: String(text) } }) }); audit("whatsapp_meta_outbound_attempt", { provider: "meta", ok: response.ok, httpStatus: response.status }); return { ok: response.ok, status: response.status, provider: "meta", messageId: response.body?.messages?.[0]?.id || null, error: response.ok ? null : "whatsapp_api_rejected_request" }; }
async function verifyConnector(id) { try { if (id === "whatsapp") { if (peachConfigured()) { const r = await fetchJson("https://app.trypeach.io/api/v1/medias", { headers: { Authorization: process.env.PEACH_API_KEY } }); const result = { id, status: r.ok ? "verified" : "error", verified: r.ok, provider: "peach", httpStatus: r.status, detail: r.ok ? "Peach API accepted the credential" : "Peach API rejected the credential" }; state.connectors.whatsapp.status = result.status; state.connectors.whatsapp.automation = r.ok ? "ready" : "verification_failed"; audit("connector_verification", { id, status: result.status, verified: result.verified, provider: "peach" }); return result; } if (process.env.WHATSAPP_ACCESS_TOKEN && process.env.WHATSAPP_PHONE_NUMBER_ID) { const r = await fetchJson(`https://graph.facebook.com/${WHATSAPP_API_VERSION}/${encodeURIComponent(process.env.WHATSAPP_PHONE_NUMBER_ID)}?fields=id,display_phone_number,verified_name`, { headers: { Authorization: `Bearer ${process.env.WHATSAPP_ACCESS_TOKEN}` } }); const result = { id, status: r.ok ? "verified" : "error", verified: r.ok, provider: "meta", httpStatus: r.status, detail: r.ok ? "Meta WhatsApp credential verified" : "Meta WhatsApp credential rejected" }; state.connectors.whatsapp.status = result.status; state.connectors.whatsapp.automation = r.ok ? "ready" : "verification_failed"; return result; } return { id, status: "needs_setup", verified: false, reason: "Peach API or Meta WhatsApp credentials missing" }; } if (id === "database") return { id, status: persistence.enabled ? "configured_unverified" : "needs_setup", verified: false }; if (id === "github" || id === "vercel") return { id, status: "verified", verified: true }; return { id, status: "needs_setup", verified: false, reason: "connector_not_configured" }; } catch { return { id, status: "error", verified: false, reason: "verification_failed" }; } }
function readiness() { const blockers = []; for (const [id, connector] of Object.entries(state.connectors)) { if (id === "database") continue; if (["needs_setup", "configured_unverified", "error"].includes(connector.status) && !["github", "vercel"].includes(id)) blockers.push({ id, status: connector.status, priority: id === "whatsapp" ? 2 : 3, owner: "user" }); } blockers.sort((a, b) => a.priority - b.priority); return { ok: blockers.length === 0, service: ZOZ_NAME, core: "healthy", persistence: persistence.enabled ? "enabled" : "memory_only", financialApprovalRequired: true, autonomy: true, blockers, business: business.businessSummary(state.business), approvalsPending: state.approvals.filter((x) => x.status === "pending").length }; }
function executionPlan() { const r = readiness(); return { service: ZOZ_NAME, mode: "ordered_execution", rule: "نفّذ تلقائيًا ما يمكن تنفيذه بأمان؛ أوقف عند اعتماد/سر/قرار مالي مطلوب", next: r.blockers, financial_actions_blocked: true }; }
function systemSelfTest() { const checks = [{ id: "express", ok: typeof app.get === "function" }, { id: "financial_gate", ok: isFinanciallySensitive("دفع 100 جنيه") && !isFinanciallySensitive("إنشاء منشور") }, { id: "business_module", ok: typeof business.businessSummary === "function" && typeof business.upsertLeadFromWhatsApp === "function" }, { id: "peach_payload_builder", ok: typeof buildPeachTemplatePayload === "function" }, { id: "peach_webhook_parser", ok: typeof normalizePeachWebhook === "function" }, { id: "cron_guard", ok: typeof authorizeCron === "function" }, { id: "whatsapp_send_guard", ok: typeof authorizeSecret === "function" }]; return { ok: checks.every((x) => x.ok), checks, testedAt: new Date().toISOString() }; }
async function executeSafeJob(job) { const sensitive = Boolean(job.financial || isFinanciallySensitive(`${job.title} ${job.description}`)); if (sensitive) { job.financial = true; if (job.status !== "approved") { job.status = "approval_required"; audit("financial_execution_blocked", { jobId: job.id }); return { executed: false, reason: "financial_approval_required" }; } job.status = "financial_execution_authorized"; audit("financial_action_authorized_not_executed", { jobId: job.id }); return { executed: false, authorized: true, reason: "financial_execution_not_configured" }; } if (job.status !== "pending") return { executed: false, reason: "not_runnable" }; job.status = "executed"; job.executedAt = new Date().toISOString(); audit("job_auto_executed", { jobId: job.id }); return { executed: true, jobId: job.id }; }
async function runAutonomousCycle() { const selfTest = systemSelfTest(); if (!selfTest.ok) return { ok: false, selfTest, executed: [] }; const verification = []; for (const id of Object.keys(state.connectors)) if (!["github", "vercel"].includes(id) && ["configured_unverified", "error"].includes(state.connectors[id].status)) verification.push(await verifyConnector(id)); const executed = [], skipped = []; for (const job of state.jobs) if (["pending", "approved"].includes(job.status)) { const result = await executeSafeJob(job); if (result.executed) executed.push(result); else skipped.push({ jobId: job.id, reason: result.reason }); } const result = { ok: true, selfTest, verification, executed, skipped, readiness: readiness() }; audit("autonomy_cycle_completed", { executed: executed.length, skipped: skipped.length, blockers: result.readiness.blockers.length }); await saveState(); return result; }
function createApproval(job) { const approval = { id: `approval_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`, jobId: job.id, type: "financial", status: "pending", requestedAt: new Date().toISOString() }; state.approvals.push(approval); return approval; }

app.get("/health", (req, res) => res.json({ ok: true, service: ZOZ_NAME, status: "healthy", persistence: persistence.enabled ? "enabled" : "memory_only", time: new Date().toISOString() }));
app.get("/api/state", (req, res) => res.json({ ...state, persistence: { enabled: persistence.enabled, provider: persistence.provider } }));
app.get("/api/readiness", (req, res) => res.json(readiness()));
app.get("/api/plan", (req, res) => res.json(executionPlan()));
app.get("/api/self-test", (req, res) => res.json(systemSelfTest()));
app.get("/api/audit", (req, res) => res.json({ events: state.audit.slice(-100) }));
app.get("/api/jobs", (req, res) => res.json(state.jobs));
app.get("/api/approvals", (req, res) => res.json(state.approvals));
app.get("/api/business/summary", (req, res) => res.json(business.businessSummary(state.business)));
app.get("/api/business/customers", (req, res) => res.json(state.business.customers));
app.get("/api/business/leads", (req, res) => res.json(state.business.leads));
app.get("/api/business/orders", (req, res) => res.json(state.business.orders));
app.get("/api/business/opportunities", (req, res) => res.json(state.business.opportunities));
app.get("/api/business/products", (req, res) => res.json(state.business.products));
app.get("/api/business/suppliers", (req, res) => res.json(state.business.suppliers));
app.get("/api/business/expenses", (req, res) => res.json(state.business.expenses));
app.post("/api/business/customers", async (req, res) => { try { const customer = business.upsertCustomer(state.business, req.body); audit("business_customer_upserted", { customerId: customer.id }); await saveState(); res.status(201).json(customer); } catch (e) { res.status(400).json({ error: e.message }); } });
app.post("/api/business/leads", async (req, res) => { try { const lead = business.addLead(state.business, req.body); audit("business_lead_created", { leadId: lead.id }); await saveState(); res.status(201).json(lead); } catch (e) { res.status(400).json({ error: e.message }); } });
app.post("/api/business/leads/:id/stage", async (req, res) => { try { const lead = business.moveLead(state.business, req.params.id, req.body.stage); audit("business_lead_stage_changed", { leadId: lead.id, stage: lead.stage }); await saveState(); res.json(lead); } catch (e) { res.status(400).json({ error: e.message }); } });
app.post("/api/business/orders", async (req, res) => { try { const order = business.createOrder(state.business, req.body); audit("business_order_created", { orderId: order.id, financialApprovalRequired: true }); await saveState(); res.status(201).json(order); } catch (e) { res.status(400).json({ error: e.message }); } });
app.post("/api/business/opportunities", async (req, res) => { try { const opportunity = business.registerOpportunity(state.business, req.body); audit("business_opportunity_registered", { opportunityId: opportunity.id }); await saveState(); res.status(201).json(opportunity); } catch (e) { res.status(400).json({ error: e.message }); } });
app.post("/api/business/actions/plan", (req, res) => res.json(business.planAction(req.body.action, req.body.payload)));
app.post("/api/jobs", async (req, res) => { const { title, description = "" } = req.body || {}; if (!title) return res.status(400).json({ error: "عنوان المهمة مطلوب" }); const financial = isFinanciallySensitive(`${title} ${description}`); const job = { id: Date.now().toString(), title, description, financial, status: financial ? "approval_required" : "pending", createdAt: new Date().toISOString() }; state.jobs.push(job); if (financial) createApproval(job); audit("job_created", { jobId: job.id, financial, status: job.status }); await saveState(); res.status(201).json(job); });
app.post("/api/jobs/:id/approve", async (req, res) => { const job = state.jobs.find((x) => x.id === req.params.id); if (!job) return res.status(404).json({ error: "المهمة غير موجودة" }); job.status = "approved"; job.approvedAt = new Date().toISOString(); const approval = state.approvals.find((x) => x.jobId === job.id && x.status === "pending"); if (approval) { approval.status = "approved"; approval.approvedAt = job.approvedAt; } audit("job_approved", { jobId: job.id, financial: job.financial }); await saveState(); res.json(job); });
app.post("/api/jobs/:id/execute", async (req, res) => { const job = state.jobs.find((x) => x.id === req.params.id); if (!job) return res.status(404).json({ error: "المهمة غير موجودة" }); const result = await executeSafeJob(job); if (result.reason === "financial_approval_required") return res.status(403).json({ error: "موافقة المستخدم مطلوبة قبل أي إجراء مالي", status: "approval_required" }); if (result.reason === "financial_execution_not_configured") return res.status(202).json({ ok: true, status: job.status, note: "تم تسجيل الموافقة البشرية فقط؛ لم يتم تنفيذ أي حركة مالية فعلية." }); await saveState(); res.json({ ok: true, job }); });
app.post("/api/replies/preview", (req, res) => { const text = req.body?.text || ""; res.json({ text, financialApprovalRequired: isFinanciallySensitive(text), ready: true }); });
app.get("/api/connectors/status", (req, res) => res.json({ ...state.connectors, persistence: { enabled: persistence.enabled, provider: persistence.provider } }));
app.get("/api/connectors/requirements", (req, res) => res.json({ whatsapp: "PEACH_API_KEY + PEACH_TEMPLATE_ID + WHATSAPP_SEND_SECRET; Meta webhook uses WHATSAPP_VERIFY_TOKEN + WHATSAPP_APP_SECRET", database: "DATABASE_URL or KV_REST_API_URL + KV_REST_API_TOKEN", cron: "CRON_SECRET", financialRule: "لا دفع أو شراء أو تحويل أو استلام أموال دون Human Approval" }));
app.get("/api/connectors/verify", async (req, res) => { const ids = req.query.id ? String(req.query.id).split(",").filter(Boolean) : ["whatsapp"]; const results = []; for (const id of ids) results.push(await verifyConnector(id)); await saveState(); res.json({ ok: results.every((x) => x.verified), results, readiness: readiness() }); });

app.get("/api/whatsapp/webhook", (req, res) => { const mode = req.query["hub.mode"], token = req.query["hub.verify_token"], challenge = req.query["hub.challenge"]; if (!process.env.WHATSAPP_VERIFY_TOKEN) return res.status(503).send("WHATSAPP_VERIFY_TOKEN not configured"); if (mode === "subscribe" && token === process.env.WHATSAPP_VERIFY_TOKEN) return res.status(200).send(challenge || ""); return res.sendStatus(403); });
app.post("/api/whatsapp/webhook", async (req, res) => { if (!isValidWhatsAppSignature(req)) return res.sendStatus(401); const events = business.normalizeWhatsAppEvent(req.body || {}); let processed = 0; for (const event of events) { if (!event.from) continue; const result = business.upsertLeadFromWhatsApp(state.business, { phone: event.from, name: event.name, request: event.text }); audit("whatsapp_lead_upserted", { messageId: event.messageId, customerId: result.customer.id, leadId: result.lead.id, created: result.created, type: event.type }); processed += 1; } audit("whatsapp_webhook_received", { events: events.length, processed }); await saveState(); res.json({ ok: true, received: events.length, processed }); });
app.post("/api/webhooks/peach", async (req, res) => { const event = normalizePeachWebhook(req.body || {}); if (!event.supported) return res.status(400).json({ ok: false, error: "unsupported_peach_event" }); audit("peach_webhook_received", publicWebhookAudit(event)); if (event.type === "message_delivery.replied") { if (!event.phone || !event.text) return res.status(400).json({ ok: false, error: "peach_reply_missing_contact_or_text" }); const result = business.upsertLeadFromWhatsApp(state.business, { phone: event.phone, name: event.name, request: event.text }); audit("peach_whatsapp_reply_crm_upserted", { messageId: event.messageId, customerId: result.customer.id, leadId: result.lead.id, created: result.created }); await saveState(); return res.status(200).json({ ok: true, event: event.type, customerId: result.customer.id, leadId: result.lead.id }); } audit("peach_message_delivery_status", { type: event.type, messageId: event.messageId, status: event.status }); await saveState(); return res.status(200).json({ ok: true, event: event.type, status: event.status || null }); });

app.post("/api/whatsapp/send", async (req, res) => { const denied = authorizeSecret(req, res, WHATSAPP_SEND_SECRET, "whatsapp_send_unauthorized"); if (denied) return; const body = req.body || {}, to = body.to, text = String(body.text || ""), liquidValues = body.liquid_values ?? body.liquidValues; const hasLiquidValues = liquidValues && typeof liquidValues === "object" && !Array.isArray(liquidValues); if (!to || (!text && !hasLiquidValues)) return res.status(400).json({ ok: false, error: "recipient_and_text_or_liquid_values_required" }); const financialInput = `${text} ${hasLiquidValues ? JSON.stringify(liquidValues) : ""}`; if (isFinanciallySensitive(financialInput)) { audit("whatsapp_outbound_blocked", { reason: "financial_approval_required" }); return res.status(403).json({ ok: false, error: "financial_approval_required" }); } try { if (peachConfigured()) { const result = await sendPeachTemplateMessage(to, { liquidValues, name: body.name, email: body.email, metadata: body.metadata, replyAutomationAppId: body.replyAutomationAppId }); return res.status(result.ok ? 200 : (result.status || 502)).json(result); } if (!text) return res.status(400).json({ ok: false, error: "text_required_for_meta_fallback" }); const result = await sendWhatsAppTextMeta(to, text); return res.status(result.ok ? 200 : (result.status || 502)).json(result); } catch (error) { audit("whatsapp_outbound_error", { message: error.message }); return res.status(502).json({ ok: false, error: "whatsapp_send_failed" }); } });

app.get("/api/automation/status", (req, res) => res.json({ mode: "safe_autonomy", financialApprovalRequired: true, financialExternalExecution: false, autonomousCycleEndpoint: "/api/automation/cycle", connectors: state.connectors, selfTest: systemSelfTest(), business: business.businessSummary(state.business), approvalsPending: state.approvals.filter((x) => x.status === "pending").length }));
app.get("/api/automation/cycle", async (req, res) => { const denied = authorizeCron(req, res); if (denied) return; try { res.json(await runAutonomousCycle()); } catch (error) { audit("autonomy_cycle_error", { message: error.message }); res.status(500).json({ ok: false, error: "autonomy_cycle_failed" }); } });
app.post("/api/automation/cycle", async (req, res) => { const denied = authorizeCron(req, res); if (denied) return; try { res.json(await runAutonomousCycle()); } catch (error) { audit("autonomy_cycle_error", { message: error.message }); res.status(500).json({ ok: false, error: "autonomy_cycle_failed" }); } });
app.get("/{*splat}", (req, res) => res.sendFile(path.join(__dirname, "public", "index.html")));
loadState().then(() => audit("system_started", { persistence: persistence.enabled, persistenceProvider: persistence.provider, financialExternalExecution: false, peachOutbound: peachConfigured(), peachWebhook: true, metaWebhook: true })).catch((error) => audit("system_start_error", { message: error.message }));
module.exports = app;
if (!process.env.VERCEL) app.listen(PORT, () => console.log(`${ZOZ_NAME} running on port ${PORT}`));
